### ISSUE TITLE
[BUG] Unable to read vertica table into Spark dataframe in Spark 3.2.1

### ISSUE THREAD

**Issue by KevinAppelBofa** [vertica/spark-connector#364]
## Environment
- Spark version: 3.2.1
- Hadoop version: 3.2.2
- Vertica version: 10.X/11.X
- Vertica Spark Connector version: 3.1.0
- Java version: 1.8
- Additional Environment Information:

---

## Problem Description
- Reading from Vertica into Spark dataframe in Spark 3.2.1 is throwing an error
- Caused by: java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.DataSourceUtils$.creteDateRebaseFuncInRead(Lscala/Enumeration$Value;Ljava/lang/String;)Lscala/Function1;

1. Steps to reproduce: Read vertica table into Spark, try to count or show
2. Expected behaviour: Provide the count or show
3. Actual behaviour: Error due to what appears to be a typo in the Vertica code
4. Error message/stack trace:
5. Caused by: java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.DataSourceUtils$.creteDateRebaseFuncInRead(Lscala/Enumeration$Value;Ljava/lang/String;)Lscala/Function1;
        at org.apache.spark.sql.execution.datasources.parquet.vertica.ParquetRowConverter.<init>(ParquetRowConverter.scala:193)
        at org.apache.spark.sql.execution.datasources.parquet.vertica.ParquetRecordMaterializer.<init>(ParquetRecordMaterializer.scala:58)
        at org.apache.spark.sql.execution.datasources.parquet.vertica.ParquetReadSupport.prepareForRead(ParquetReadSupport.scala:141)
        at com.vertica.spark.datasource.fs.HadoopFileStoreLayer.$anonfun$openReadParquetFile$1(FileStoreLayerInterface.scala:327)
        at scala.util.Try$.apply(Try.scala:213)
        at com.vertica.spark.datasource.fs.HadoopFileStoreLayer.openReadParquetFile(FileStoreLayerInterface.scala:316)
        at com.vertica.spark.datasource.core.VerticaDistributedFilesystemReadPipe.$anonfun$startPartitionRead$2(VerticaDistributedFilesystemReadPipe.scala:375)
        at scala.util.Either.flatMap(Either.scala:341)
        at com.vertica.spark.datasource.core.VerticaDistributedFilesystemReadPipe.startPartitionRead(VerticaDistributedFilesystemReadPipe.scala:362)
        at com.vertica.spark.datasource.core.DSReader.openRead(DSReader.scala:65)
        at com.vertica.spark.datasource.v2.VerticaBatchReader.<init>(VerticaDatasourceV2Read.scala:232)
        at com.vertica.spark.datasource.v2.VerticaReaderFactory.createReader(VerticaDatasourceV2Read.scala:220)
        at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD.compute(DataSourceRDD.scala:64)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:131)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more
6. Code sample or example on how to reproduce the issue:
df1 = spark.read.load(format="com.vertica.spark.datasource.VerticaSource",
 host=host,
 user=user,
 password=password,
 db=db,
 dbschema="my_schema",
 table="my_table",
 staging_fs_url=staging_fs_url)

df1.count)
---

## Spark Connector Logs
- Add related logs entries here.

**Comment by KevinAppelBofa** [comment]
This looks like Line 192, 195, and 198 of https://github.com/vertica/spark-connector/blob/main/connector/src/main/scala/com/vertica/spark/parquet/ParquetRowConverter.scala

The Spark code the function name is having an a in all of these, it should say create not crete

**Comment by Aryex** [comment]
Hi Kevin. We'll be looking into this issue.
