### ISSUE TITLE
Weekly CI tests (S3) fail

### ISSUE THREAD

**Issue by jeremyp-bq** [vertica/spark-connector#493]
## Environment

Latest version as of September 5, 2022.

---

## Problem Description

Noticed that the Weekly Tests failed during the S3 tests with the following error:
```
22/09/05 10:51:27 ERROR Main$: Uncaught exception from tests: Error getting file list from ***/
org.scalatest.exceptions.TestFailedException: Error getting file list from ***/
	at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:472)
	at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:471)
	at org.scalatest.flatspec.AnyFlatSpec.newAssertionFailedException(AnyFlatSpec.scala:1685)
	at org.scalatest.Assertions.fail(Assertions.scala:933)
	at org.scalatest.Assertions.fail$(Assertions.scala:929)
	at org.scalatest.flatspec.AnyFlatSpec.fail(AnyFlatSpec.scala:1685)
	at com.vertica.spark.functests.endtoend.EndToEnd.afterEach(EndToEndTests.scala:71)
        ...
```

When the action was run again (no code changes), it worked without issue. So this was an intermittent error, not sure how to reproduce.

**Comment by jeremyp-bq** [comment]
Cannot reproduce.
